CREATE TABLE list (book_id integer,
                   title text,
                   title_yomi text,
                   title_sort text,
                   subtitle text,
                   subtitle_yomi text,
                   original_title text,
                   first_appearance text,
                   ndc_code text,
                   font_kana_type text,
                   copyright boolean,
                   release_date timestamp without time zone,
                   last_modified timestamp without time zone,
                   card_url text,
                   person_id integer,
                   last_name text,
                   first_name text,
                   last_name_yomi text,
                   first_name_yomi text,
                   last_name_sort text,
                   first_name_sort text,
                   last_name_roman text,
                   first_name_roman text,
                   role text,
                   date_of_birth text,
                   date_of_death text,
                   author_copyright boolean,
                   base_book_1 text,
                   base_book_1_publisher text,
                   base_book_1_1st_edition text,
                   base_book_1_edition_input text,
                   base_book_1_edition_proofing text,
                   base_book_1_parent text,
                   base_book_1_parent_publisher text,
                   base_book_1_parent_1st_edition text,
                   base_book_2 text,
                   base_book_2_publisher text,
                   base_book_2_1st_edition text,
                   base_book_2_edition_input text,
                   base_book_2_edition_proofing text,
                   base_book_2_parent text,
                   base_book_2_parent_publisher text,
                   base_book_2_parent_1st_edition text,
                   input text,
                   proofing text,
                   text_url text,
                   text_last_modified timestamp without time zone,
                   text_encoding text,
                   text_charset text,
                   text_updated integer,
                   html_url text,
                   html_last_modified timestamp without time zone,
                   html_encoding text,
                   html_charset text,
                   html_updated integer,
                   CONSTRAINT id_ukey UNIQUE(book_id, person_id))
